### ISSUE TITLE
Shipping method not added successfully

### ISSUE THREAD

**Issue by unclegusy2k** [weDevsOfficial/dokan#1867] opened 2023-04-25 15:05 UTC
Every time i try to add a shipping method i get

Shipping method not added successfully

can anyone help please?
![error](https://user-images.githubusercontent.com/54286197/234320172-05b94ac9-7ded-49a6-8fdb-3d1f65811c87.png)

**Comment by nurul-umbhiya** [comment] 2023-04-25 15:14
@unclegusy2k Kindly create a support ticket, without looking into your site, can't tell for sure what went wrong.
I'll definitely change the Error message though.

**Comment by unclegusy2k** [comment] 2023-04-25 15:34
![Screenshot_20230425-163331](https://user-images.githubusercontent.com/54286197/234328414-e68abfa8-30d3-411c-af76-493d800e5c50.png)


I already have and still waiting for a response

**Comment by unclegusy2k** [comment] 2023-04-26 04:52
@nurul-umbhiya can you help with this? I still haven't had a response

**Comment by shohag121** [comment] 2023-05-24 03:27
@tanjiralmamun,

Would you kindly let us know the progress or status of the support ticket or the findings?

**Comment by tanjiralmamun** [comment] 2023-05-24 04:46
@shohag121 bhai, we did not find any purchase history of the user. Without confirming the purchase, we cannot provide support for any premium features.

**Comment by shohag121** [comment] 2023-05-29 05:05
Hi @unclegusy2k,

As we need additional information regarding the error and to figure out the cause of the issue, please contact the support team with the information they need.

I am closing the issue here for now.

**Closed by shohag121** 2023-05-29 05:05 UTC
