### ISSUE TITLE
Make price field required

### ISSUE THREAD

**Issue by leew999** [weDevsOfficial/dokan#1498] opened 2022-01-17 18:20 UTC
for my last 7 users who submitted their product, there were 3 of them missing the price field. please see here https://imgur.com/a/7pqZBMr  , for the simple product and variable product I suggest to make the price field " required" , otherwise as admin I have no way to keep inform users that they need to enter their product price.

**Comment by Tangol** [comment] 2022-01-17 21:03
Duplicate of https://github.com/weDevsOfficial/dokan/issues/1258

**Comment by leew999** [comment] 2022-01-17 22:38
can this be added into the new release ? I see the #1258 was there for more than 6 months already, thanks

**Comment by leew999** [comment] 2022-01-25 12:05
any idea when this can be added into the new release or we have to spend time ourself to deal with this ? at the moment, almost 50% of the vendors are missing the price field after they create the product.

**Comment by nurul-umbhiya** [comment] 2022-01-25 12:30
for now, you can use the code in this pr: https://github.com/Riyadh1734/dokan/commit/8d340e45e40df8753a4e4c9d2b9c03457cb83143
add this in your theme's function.php file. The version we are working on right now will be cooked by February.

**Comment by leew999** [comment] 2022-01-26 11:46
@nurul-umbhiya thanks, the code works on the "create product" page. but it doesn't work on the "edit product" page when vendor select the variable product,   for my another 2 post here #1508 and #1459 I suggested to bring the attribute/variable section into the first create product page, most of the users are not software expert they  found difficult to understand how to deal with the attribute/variable, and for sure they will miss the price input when they select the variable product here.

**Comment by nurul-umbhiya** [comment] 2023-06-02 08:15
closing duplicate entries

**Closed by nurul-umbhiya** 2023-06-02 08:15 UTC
Labels: Enhancement, Analysis
