### ISSUE TITLE
Fix: Cash on Delivery Issue/Bug with Commission, Vendor Earnings and Withdrawal Balance

### ISSUE THREAD

**Issue by oudin** [weDevsOfficial/dokan#837] opened 2020-05-19 16:35 UTC
I see this issue https://github.com/weDevsOfficial/dokan/issues/34 opened in 2017 https://github.com/weDevsOfficial/dokan/issues/433 and again raised in 2018. However, it still exists in 2020.

This is what we need done for COD. I want disabled.

1. Calculation of COD commissions and adding COD commission to Total Dokan commission.
2. Calculation of COD Vendors earnings and adding COD earnings to total Dokan Vendor earnings and Dokan withdrawal balance/total.

Simply, add settings in the plugin to disable the above for Admins who wish to do so.

This will enable Dokan to have accurate commissions, earnings, and withdrawal numbers for online transactions/payments only. The Admin can then charge Vendors an additional monthly/annual fee manually or use subscriptions to cover COD or other offline transactions/payments. 

How can this be fixed?

Thanks

**Comment by saimonh3** [comment] 2020-05-22 03:25
@oudin COD payment is in our backlog. We'll add that feature soon. Thanks
Duplicate of #34

**Closed by saimonh3** 2020-05-22 03:25 UTC

**Comment by oudin** [comment] 2020-06-05 14:33
> We'll add that feature soon. 

@saimonh3 It's been 3-4 years now. How soon is soon? Thanks

**Comment by vincebuck** [comment] 2021-06-02 14:57
This is again one year ago and still nothing happened? When will that soon be?
