### ISSUE TITLE
Hint text wrong when "Allow vendors to create new product tags.."

### ISSUE THREAD

**Issue by leew999** [weDevsOfficial/dokan#1237] opened 2021-06-09 10:26 UTC
When "Allow vendors to create new product tags from vendor dashboard." enabled, the hint text showing on the tags field still " Select tags" [https://imgur.com/a/9oyUQKi](url)

**Comment by Tangol** [comment] 2021-06-09 10:50
Not a bug, in my opinion.
When `Allow vendors to create new product tags from vendor dashboard.` is active, the user can select from an existing tag or create a new one if what he entered doesn't exist.
So in this case, `Select tags` accounts for both adding and selection and it's the right text.

**Comment by leew999** [comment] 2021-06-09 10:56
if you think this is right, then how vendor knows they are allowed to enter new tags ? no field description, they will think they only can select existing tags from the dropdown by reading the hint text.

**Comment by Tangol** [comment] 2021-06-09 11:10
The vendor will know just by entering the tag. If tag adding is allowed, then the new tag he entered, will appear in the product description.
If not, then it doesn't.

However, to make it more clear, the placeholder text could have `/Add tags` added to it when `Allow vendors to create new product tags from vendor dashboard.` is enabled.
If its disabled, then it will only show `Select tags`.
Something like:
![tags](https://user-images.githubusercontent.com/3336728/121344108-084dea00-c92c-11eb-8fd8-911c5d160642.png)

**Comment by leew999** [comment] 2021-06-09 11:24
1: yes, 
"the placeholder text could have /Add tags added to it when Allow vendors to create new product tags from vendor dashboard. is enabled. If its disabled, then it will only show Select tags."

2: "The vendor will know just by entering the tag" , how vendor will know? they won't know. 

Thanks

**Comment by Tangol** [comment] 2021-06-09 11:33
@alamgircsebd could you please squeeze this in https://github.com/weDevsOfficial/dokan/pull/1234

**Comment by alamgircsebd** [comment] 2021-06-10 05:24
This issue resolved with this pull request https://github.com/weDevsOfficial/dokan/pull/1234

**Closed** 2021-06-29 15:37 UTC
Labels: Bug, Has Pull Request
