### ISSUE TITLE
show Store support button by default

### ISSUE THREAD

**Issue by leew999** [weDevsOfficial/dokan#1561] opened 2022-03-08 21:40 UTC
my previous require closed, so I open again, this is a real problem on my site. I try to replicate the problem on a new test site, and I got the same so the process is below :

1: admin enable the "Display Store Support button on the order details page for customer" on the setting/store-support page first.
2: vendor after registration and login to his dashboard, create a new product, there will be no "Get support" button showing on the product page
3: Vendor go to dashboard/setting page, by default, the "Support Button text" is empty, only a placeholder text "Get Support" showing, if you don't enter any text into the field, there will be no button showing on the product page, some people might think the placeholder text is the button text, its creating confusion. 
4: After vendor enter the text into the "Support Button text" field, click "Update setting" . the page will showing error because the "Country" filed is required on the same page, please see here https://imgur.com/a/JxTJIDh , so at the end, vendor need to select his country first, enter the button text into the button field, to get the button showing on his product page.

There are about none of my vendors are showing the "Get support" button on my site, total about 100 vendors at the moment. I believe none of them will go through the setting page to enter the text on the button field to get the button display. 

My understanding is, once admin enable the store support button, the button should show by default,  the vendor can change the button text always, but vendor should not have to enter the button text to get it display. Thanks

**Comment by nurul-umbhiya** [comment] 2022-03-11 12:18
@leew999 kindly create a support ticket for this and mention your ticket number here. I'm getting a hard time reproducing this issue on my end.

**Comment by leew999** [comment] 2022-03-11 12:23
I was simply just install a new site with only dokan's plugin, admin enable the button setting, then register as a vendor to post a product, then you can see the problem.

**Comment by devAsadNur** [comment] 2023-05-30 10:22
@leew999 Thanks for reporting the issue. But, we couldn't reproduce the issue from our end by using the latest version of `Dokan Lite` and `Dokan Pro`. So, we're closing the issue. 

If you still face the issue from your end, feel free to create a support ticket. We'll be happy to assist you. Thanks again.

**Closed by devAsadNur** 2023-05-30 10:22 UTC
Labels: Feature Request
