### ISSUE TITLE
Checkout blocked with "SyntaxError in JSON" with PayPal Marketplace module 

### ISSUE THREAD

**Issue by ProRealCode** [weDevsOfficial/dokan#1556] opened 2022-03-07 15:07 UTC
Hello, 

While testing the Dokan PayPal Marketplace module in sandbox mode, the checkout always result in an JSON error: 
**SyntaxError: Unexpected token < in JSON at position 2**
![image](https://user-images.githubusercontent.com/23722067/157059005-105acbd5-3ae9-4e66-b6b1-a38fa986f823.png)

After payment this error flash on the checkout page and WC  do not automatically go the thank you page (as it normally do with any other payment gateway).

The payment is correctly made through PayPal for the vendor, but there is no commission reverted to the marketplace (or splitted), complete payment go the vendor as per the dokan logs: 
![image](https://user-images.githubusercontent.com/23722067/157060462-9ea6e6e3-74b8-4592-bc39-68ee41db1eec.png)
This might be because of the JSON error?!

Tests were made with Dokan Pro 3.5.2., with default WP theme.

**Comment by ProRealCode** [comment] 2022-03-07 16:28
Error message more detailed in Firefox: 
![image](https://user-images.githubusercontent.com/23722067/157075697-56fd11b1-2d39-4998-976a-497beaa80bb8.png)

**Comment by nurul-umbhiya** [comment] 2022-03-07 16:41
kindly set WP_DEBUG to false and try again, Also create a support ticket with your site details. We'll have a look into this.

**Comment by ProRealCode** [comment] 2022-03-07 16:52
with WP_DEBUG set to false, sometimes the JSON error is not present and the website goes successfully to the thank you page, but it works 1/10 only. Still, in any case, no commission earned. All money go to vendors.

**Comment by ProRealCode** [comment] 2022-03-08 09:16
I find out that if the product is set as "virtual" the application commission is 0€.
If the product is not "virtual" (checkbox unchecked), then the application commission is correctly calculated. Hope it helps others.

**Comment by ProRealCode** [comment] 2022-03-08 13:47
For the record, I found that the platform fee are not delivered to the platform partner account in sandbox (seems a normal behavior with sandbox). BTW, the platform fees (partner commission) are visible in each of the vendor transaction details: 
![image](https://user-images.githubusercontent.com/23722067/157250455-12a6a7b1-cb4b-4b61-b9d0-b851087256dd.png)

**Comment by nurul-umbhiya** [comment] 2022-03-08 13:52
@ProRealCode kindly refer to this documentation: https://developer.paypal.com/docs/multiparty/reports/
Admin commission doesn't show up on admin account, end of the day commission will be sent directly to linked bank account. To get commission report, you need to setup sftp.

**Comment by ProRealCode** [comment] 2022-03-08 13:55
@nurul-umbhiya thanks, very useful!

**Comment by nurul-umbhiya** [comment] 2022-08-02 08:46
@ProRealCode I'm closing this issue since we couldn't reproduce this issue. Kindly let me know if this issue still exists on your end.

**Closed by nurul-umbhiya** 2022-08-02 08:46 UTC
Labels: Bug
