### ISSUE TITLE
Vendors unable to edit settings

### ISSUE THREAD

**Issue by fisher2470** [weDevsOfficial/dokan#1631] opened 2022-06-16 20:26 UTC
**Describe the bug**
Some vendors are unable to update their settings after changing profile pictures, or banner images. Instead, a datepicker receives focus in the top left of the screen. It appears the JS handler for the update button can become decoupled from the update function.

I have not been able to reproduce this bug reliably, but it has occurred with multiple versions of Dokan/Dokan Pro on my staging and my live site. 

I used the troubleshooting plugin to rule out the possibility that this is caused by a plugin conflict. 

**Screenshots**
Below is the image of the date picker being opened
![image](https://user-images.githubusercontent.com/42970431/174157369-6b70ec79-0332-4a14-9213-3f2c8ff2a166.png)

**Additional context**
I fixed the issue on my site by using JQuery to add the form id and the submit action to the top-right update button on page load, but a more permanent solution may be necessary. 

The file /templates/settings/header.php is responsible for loading the dokan-update-setting-top-button button, adding the form action here would prevent this issue from occurring for other users.

**Comment by nurul-umbhiya** [comment] 2022-11-01 03:33
@fisher2470 is this issue still exist? I can't reproduce this issue on my end.

**Comment by devAsadNur** [comment] 2023-03-01 06:03
I'm closing the issue as it can't be reproduced from our end. Later, it can be re-opened if found again.

**Closed by devAsadNur** 2023-03-01 06:03 UTC
Labels: Bug
