### ISSUE TITLE
"Update from favorite store" email showing private coupon

### ISSUE THREAD

**Issue by ProRealCode** [weDevsOfficial/dokan#1835] opened 2023-03-15 09:28 UTC
Hi, 
When a user follows a vendor, he/she receives periodic updates from the vendor. But these emails also include coupon codes that are "private", which are intended for certain users only, since they are designated by their email addresses in the coupon creation interface.
Could you change the email updates to prevent this from happening?

**Comment by nurul-umbhiya** [comment] 2023-05-29 05:44
@ProRealCode We couldn't reproduce this issue with our multiple testing. Closing this issue for now.

**Closed by nurul-umbhiya** 2023-05-29 05:44 UTC
Labels: Bug, Needs Testing
