### ISSUE TITLE
Stripe Express > Announcement Interval Settings not respected and announcement notification sent 3 times in a row

### ISSUE THREAD

**Issue by Sophie-2e** [weDevsOfficial/dokan#1960] opened 2023-08-11 08:07 UTC
**Describe the bug**
Stripe Announcement Sent 3 times in a row when vendors are not connected - no respect for the announcement interval settings 

Sellers receive the announcement 3 times in a row, right after each other, while in the settings (wp-admin/admin.php?page=wc-settings&tab=checkout&section=dokan_stripe_express), the announcement interval is set up to 7 in my case. 

I got in touch with your team on support ticket #331689 who also experienced the same issue however, 1 month and a few Dokan updates later, the issue is still not resolved and I do not see anything about it on your GitHub so that is why I am opening this card. 

**To Reproduce**
Steps to reproduce the behaviour:
Use Stripe Express payment to receive Vendors' Subscription
In Woocommerce Settings > Payment > Stripe Express > Enable the option "Send Announcement to Non-connected Sellers"
In Woocommerce Settings > Payment > Stripe Express > Sert the Announcement Interval on 7 (for 7 days, so once a week)
Create a new seller account and do not proceed with the Stripe Onboard process during Vendor Wizard
Check the vendor's email > You will have received 3 time the same Stripe announcement

**Expected behaviour**
That the Stripe Announcement Interval Settings got respected.

**Screenshots**
Please check ticket: #331689

**Environment (please complete the following information):**
 - Dokan Version: 3.7.24
 - Dokan Pro Version: 3.7.30
 - WooCommerce Version: Version 8.0.1
 - Current Theme: Blocksy, but same issue with any theme

**Comment by nurul-umbhiya** [comment] 2023-08-16 03:33
I couldn't reproduce this issue on my end. Is there any way you are using an object cache plugin?
I'm closing this issue for now. Kindly create a support ticket for this since this is only happening on your end. We will take it from there.

**Closed by nurul-umbhiya** 2023-08-16 03:33 UTC
Labels: Bug
