### ISSUE TITLE
Decimal as comma separated sale price does not save

### ISSUE THREAD

**Issue by rashedripon** [weDevsOfficial/dokan#1176] opened 2021-04-18 07:23 UTC
**Describe the bug**
When using a comma-separated decimal price is used the sale price does not save properly.

**To Reproduce**
1. Make sure to use the decimal separator as "comma" under WooCommerce > Settings > General
2. Edit the product in the vendor dashboard and set the prices like this -
 - regular price: 12,50 - sales price 5,50
3. Save the product
4. See the sale price is not saved.

**Expected behavior**
Any price set as a sale price should be saved.

**Environment (please complete the following information):**
 - Dokan Version: 3.2.4
 - Dokan Pro Version: 3.2.2
 - WooCommerce Version: 5.2.2

**Comment by shohag121** [comment] 2021-04-19 10:26
Hello @rashedripon,
I'm closing this issue as it could not be reproduced.
Please see the video https://youtu.be/Gpp7QllPqqM for details about the step and test result.

Please contact me if I missed something.
Shohag

**Comment by rashedripon** [comment] 2021-04-24 01:01
Hello @shohag121 please try again with these type of values:
regular price: 12,50 - sales price 5,50
regular price: 20,50 - sales price 8,50

It does not occur if I use for example 20,10 and 13,20

**Comment by huwcole** [comment] 2021-05-02 22:27
hi 
it was me who submitted this bug...

How to Reproduce The Bug
1. make sure you have set price to comma seperated in woocommerce->settings->general tab 2. go to vendors dashboard and add a new product or use an existing one 3. add a sales price it works for following scenario: 1. regular price: 12,50 - sales price 10,50 2. regular price: 9,50 - sales price 5,50 it does not work for following scenarios: 1. regular price: 12,50 - sales price 5,50 2. regular price: 19,50 - sales price 9,50 the price will be empty because for some reason your code thinks the following is happening: "if regular price is lower than sale price then we are setting it to empty" though that is not the case.


/dokan-lite/includes/wc-functions.php

line 76

change code to below and it will then work, that's what i use now, but i would like you guys to fix this so that i don't have to override your core file everytime you do an update:

if ( isset( $data['_sale_price'] ) ) {
        //if regular price is lower than sale price then we are setting it to empty
        if ( wc_format_decimal($data['_regular_price']) <= wc_format_decimal($data['_sale_price'] )) {
            $data['_sale_price'] = '';
        }

        update_post_meta( $post_id, '_sale_price', ( $data['_sale_price'] === '' ? '' : wc_format_decimal( $data['_sale_price'] ) ) );
    }

**Comment by huwcole** [comment] 2021-05-03 13:01
Hello @shohag121 please try again. see my comment @huwcole

**Comment by nurul-umbhiya** [comment] 2021-05-03 13:21
@huwcole we are looking at this issue and this will be fixed in the next release of Dokan. Thank you for your effort on this.

**Closed** 2021-05-07 09:07 UTC
Labels: Bug, Has Pull Request
