### ISSUE TITLE
make product description field "required"

### ISSUE THREAD

**Issue by leew999** [weDevsOfficial/dokan#1470] opened 2021-12-22 11:38 UTC
we are getting empty product description from vendors, see here https://imgur.com/a/b5xGZ8k  , after enter the short description field, vendor ignore the description field, its a small thing, but makes the website look bad.

**Comment by Tangol** [comment] 2021-12-22 15:01
Duplicate of https://github.com/weDevsOfficial/dokan/issues/1258

**Comment by nurul-umbhiya** [comment] 2023-06-02 08:14
Closing duplicate entries.

**Closed by nurul-umbhiya** 2023-06-02 08:14 UTC
Labels: Enhancement
