### ISSUE TITLE
Setting for the order of product category list

### ISSUE THREAD

**Issue by leew999** [weDevsOfficial/dokan#1248] opened 2021-06-11 14:47 UTC
We need a setting for the order of the product category list. think about this, in most of the case, we need a category call "Other" which will be shown on the last of the list, its pretty fundamental. my site has 10 parent categories, there is a list of child categories showing under each of the parent category, each of them need to have a "Other" showing as the last one, but now, I can't do this.

**Comment by Tangol** [comment] 2021-06-11 14:49
Duplicate of https://github.com/weDevsOfficial/dokan/issues/1238
Can be closed.

**Comment by leew999** [comment] 2021-06-16 10:18
I think this is not only need to be in the alphabetical order, it need a setting for the order of the list.  think about this, in most of the case, we need a category call "Other" which will be shown on the last of the list, its pretty fundamental.  my site has 10 parent categories, there is a list of child categories showing under each of the parent category, each of them need to have a "Other" showing as the last one, but now, I can't do this.

**Comment by Tangol** [comment] 2021-06-16 10:25
You can edit the report title and the description. 
The sort order was fixed in https://github.com/weDevsOfficial/dokan/pull/1255

Thanks!

**Comment by nurul-umbhiya** [comment] 2021-09-06 05:23
Alreay fixed.

**Closed by nurul-umbhiya** 2021-09-06 05:23 UTC
Labels: Bug
